VERSION = "2026.06.14 AI REDAKTOR BOT FINAL HOTFIX — TEST PUBLISH, FORCED AUTOPUBLISH, ITERATIVE QUALITY"
PROJECT_NAME = "Мир на ладони — AI-редакция travel Telegram-канала"
BOT_CODENAME = "AI_REDAKTOR_BOT_FINAL"
