VERSION = "2026.06.16 AI REDAKTOR BOT FINAL HOTFIX — ASYNC AUTOPUBLISH, UNIQUE TOPICS, SINGLE REWRITE, RATINGS MEMORY"
PROJECT_NAME = "Мир на ладони — AI-редакция travel Telegram-канала"
BOT_CODENAME = "AI_REDAKTOR_BOT_FINAL"
