VERSION = "2026.06.13 AI REDAKTOR BOT FINAL — ITERATIVE QUALITY, ADMIN RATINGS, VISUAL TELEGRAM STYLE"
PROJECT_NAME = "Мир на ладони — AI-редакция travel Telegram-канала"
BOT_CODENAME = "AI_REDAKTOR_BOT_FINAL"
